### ISSUE TITLE
Automatically increment slot numbers

### ISSUE THREAD

**Issue by felixlinker** [GermanHydrogen/Registration-Bot#7]
Whenever events are created, the bot takes the slot numbers from the post of the event creator. I think it would be better to assign the numbers automatically. This requires less maintenance for organizors.

Additional ideas:
 * Only automatically increment numbers, if the slot ID is 0, e.g. `#00`.
 * Add leading zeros as long as the number has fewer digits than the number provided, e.g. if `#00` should be replaced by a three, replace it with `#03`.

**Comment by GermanHydrogen** [comment]
This feature is now implemented
